const SET_USER = "SET_USER";
const SET_ISLOADING = "SET_ISLOADING";
const SET_APPLICATIONS = "SET_APPLICATIONS";
const SET_SEARCH = "SET_SEARCH";
const SET_APP_ISLOADING = "SET_APP_ISLOADING";

export {
  SET_USER,
  SET_ISLOADING,
  SET_APPLICATIONS,
  SET_SEARCH,
  SET_APP_ISLOADING,
};
