const SET_USER = "SET_USER";
const SET_ISLOADING = "SET_ISLOADING";
const SET_APPLICATIONS = "SET_APPLICATIONS";
const SET_SEARCH = "SET_SEARCH";

export { SET_USER, SET_ISLOADING, SET_APPLICATIONS, SET_SEARCH };
